### ISSUE TITLE
Punish doesn't work

### ISSUE THREAD

**Issue by RealFriesi** [Twentysix26/Red-Cogs#55]
punish can't set the channel rights.

```
[07/08/2016 23:53] ERROR red on_command_error 92: Exception in command 'punish'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/opt/Red-DiscordBot/cogs/punish.py", line 33, in punish
    await self.bot.edit_channel_permissions(c, r, deny=perms)
TypeError: edit_channel_permissions() got an unexpected keyword argument 'deny'
```

**Comment by Kowlin** [comment]
Get the latest version from here. https://github.com/Kowlin/refactored-cogs I'm not updating it here.
